name: build

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 10 * * 1' # Run on 10:00 AM every Monday
  workflow_call:
    inputs:
      skipTests:
        description: 'Skip tests, useful when there is a dediactewd CI job for the tests'
        default: true
        required: false
        type: boolean

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5 # 5 minutes timeout
    strategy:
      fail-fast: true
      matrix:
        go: [ 'stable' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4

      - name: Go mod verify
        uses: go mod verify

      - name: Go format
        uses: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go mod download
        run: go mod download

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go build
        run: Go build -o /dev/null ./...







