name: lint

on:
  pull_request:
    branches: [master]
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [1.22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
